// GENERATED BY scripts/derive.py FROM scripts/canon.py -- DO NOT EDIT BY HAND.
// Edit scripts/canon.py and re-run:  python scripts/derive.py
// Rationale: docs/ARCHITECTURE.md Sec 5 (Anti-drift machinery).

#pragma once

// Physics-oracle expectations. Every value is computed by scripts/derive.py from
// first principles -- the tests assert that the SIMULATION reproduces them.
// See docs/VERIFICATION.md for the full derivation report.

namespace astro::expected {

inline constexpr double T1_V_SETTLE_FULL = 0.001681466150184778; // [m/s] Stokes terminal velocity, fully charged cell (down)
inline constexpr double T1_V_SETTLE_FULL_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T2_V_RISE_EMPTY = -5.2107311428206046e-05; // [m/s] Stokes terminal velocity, empty cell (negative = rises)
inline constexpr double T2_V_RISE_EMPTY_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T3_CHARGE_NEUTRAL = 0.030057746373045747; // [-] Charge fraction at neutral buoyancy
inline constexpr double T3_CHARGE_NEUTRAL_TOL = 0.001; // relative tolerance
inline constexpr double T4_DIFFUSIVITY_20C = 4.2869152950615823e-14; // [m^2/s] Einstein-Stokes D = kT/gamma at 20 C
inline constexpr double T4_DIFFUSIVITY_20C_TOL = 0.029999999999999999; // relative tolerance
inline constexpr double T4_RMS_DISP_1S_20C = 4.1409734580465895e-07; // [m] 2D RMS displacement in 1 s, MSD = 4Dt
inline constexpr double T4_RMS_DISP_1S_20C_TOL = 0.029999999999999999; // relative tolerance
inline constexpr double T5_DELTA_MASS_FULL = 1.6689750840804278e-11; // [kg] Mass gained charging 0 -> 1.5 MJ
inline constexpr double T5_DELTA_MASS_FULL_TOL = 1.0000000000000001e-09; // relative tolerance
inline constexpr double T6_THRUST_1MW = 3.3356409519815207e-12; // [N] Photon thrust F = P/c at P = 1 mW
inline constexpr double T6_THRUST_1MW_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T6_VTERM_1MW = 3.5330600438173766e-05; // [m/s] Terminal velocity under 1 mW thrust
inline constexpr double T6_VTERM_1MW_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T7_CONDUCTION_20C = 0.0028711750393838067; // [W] Heat loss of an awake cell into 20 C water
inline constexpr double T7_CONDUCTION_20C_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T7_ENDURANCE_20C = 522434187.89330256; // [s] Time to drain 1.5 MJ at that rate
inline constexpr double T7_ENDURANCE_20C_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T8_REYNOLDS_FULL = 0.01675515859720306; // [-] Reynolds number at max terminal velocity; must stay << 1
inline constexpr double T8_REYNOLDS_FULL_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double T12_DIFFUSIVITY_SETPOINT = 1.8678155730650127e-13; // [m^2/s] D at the setpoint temperature (drives P4)
inline constexpr double T12_DIFFUSIVITY_SETPOINT_TOL = 0.029999999999999999; // relative tolerance
inline constexpr double T12_MOTILITY_RATIO = 4.3570153467148947; // [-] Live/dead Brownian mobility ratio
inline constexpr double T12_MOTILITY_RATIO_TOL = 0.029999999999999999; // relative tolerance
inline constexpr double T15_KOMOROV_ENERGY = 1500000; // [J] Dimitri's laser: 1 kW x 25 min
inline constexpr double T15_KOMOROV_ENERGY_TOL = 0.001; // relative tolerance
inline constexpr double T15_KOMOROV_MASS = 1.6689750840804278e-11; // [kg] Mass gained in the Komorov experiment
inline constexpr double T15_KOMOROV_MASS_TOL = 0.001; // relative tolerance
inline constexpr double T16_PHOTON_ENERGY = 7.6448809157517267e-21; // [J] Petrova photon energy
inline constexpr double T16_PHOTON_ENERGY_TOL = 0.0001; // relative tolerance
inline constexpr double T17_PETROVA_FREQ = 11537579202586.207; // [Hz] Petrova frequency
inline constexpr double T17_PETROVA_FREQ_TOL = 0.0001; // relative tolerance
inline constexpr double T20_WIEN_SETPOINT = 7.8410346082556516e-06; // [m] Thermal blackbody peak; must differ from the Petrova line
inline constexpr double T20_WIEN_SETPOINT_TOL = 0.0001; // relative tolerance
inline constexpr double HOVER_POWER_FULL = 0.047592345709698128; // [W] Emission power a full cell needs to hover
inline constexpr double HOVER_POWER_FULL_TOL = 0.0050000000000000001; // relative tolerance
inline constexpr double TAU_MOMENTUM_EMPTY = 2.2242879850749579e-07; // [s] Momentum relaxation time, empty cell
inline constexpr double TAU_MOMENTUM_EMPTY_TOL = 9.9999999999999995e-07; // relative tolerance
inline constexpr double TAU_MOMENTUM_FULL = 0.00017699772531801049; // [s] Momentum relaxation time, full cell
inline constexpr double TAU_MOMENTUM_FULL_TOL = 9.9999999999999995e-07; // relative tolerance

} // namespace astro::expected
