// GENERATED BY scripts/derive.py FROM scripts/canon.py -- DO NOT EDIT BY HAND.
// Edit scripts/canon.py and re-run:  python scripts/derive.py
// Rationale: docs/ARCHITECTURE.md Sec 5 (Anti-drift machinery).

#pragma once

namespace astro::canon {

enum class Provenance : unsigned char { Canon = 0, Derived = 1, Real = 2, Invented = 3 };

// ---- Universal constants -------------------------------------------------
inline constexpr double C_LIGHT = 299792458; // [m/s] exact by definition
inline constexpr double K_BOLTZ = 1.3806490000000001e-23; // [J/K] exact by definition
inline constexpr double H_PLANCK = 6.6260701499999998e-34; // [J*s] exact by definition
inline constexpr double G_ACCEL = 9.8066499999999994; // [m/s^2] standard gravity
inline constexpr double SIGMA_SB = 5.6703744189999999e-08; // [W/m^2/K^4] Stefan-Boltzmann
inline constexpr double EV_JOULE = 1.6021766339999999e-19; // [J/eV] exact by definition
inline constexpr double WIEN_B = 0.002897771955; // [m*K] Wien displacement
inline constexpr double TNT_JOULE = 4184; // [J/g] 1 g TNT equivalent

// ---- Base parameters (see scripts/canon.py for provenance) ---------------
inline constexpr double CELL_DIAMETER = 1.0000000000000001e-05; // [m] CANON -- 10 micron sphere.
inline constexpr double CELL_MASS_DRY = 2.0999999999999999e-14; // [kg] CANON -- 0.021 ng. Conflicts with 'mostly water' -- see ADR-002.
inline constexpr double CELL_TEMP_SETPOINT = 369.565; // [K] CANON -- 96.415 C. NOT a frequency -- see ADR-001.
inline constexpr double CELL_ENERGY_MAX = 1500000; // [J] CANON -- 1.5 MJ per cell at full enrichment.
inline constexpr double CELL_ALBEDO = 0; // [-] CANON -- Opaque at ALL wavelengths (super cross-sectionality).
inline constexpr double CELL_ALBEDO_DEAD = 0.84999999999999998; // [-] INVENTED -- Dead cells go translucent; degree unstated.
inline constexpr double CELL_LETHAL_TEMP = 573.14999999999998; // [K] INVENTED -- 300 C. Torch-the-slide escape hatch; canon silent.
inline constexpr double PETROVA_WAVELENGTH = 2.5984000000000001e-05; // [m] CANON -- 25.984 micron. NOT 3.11 um -- see ADR-001.
inline constexpr double PETROVA_BEAM_HALF_ANGLE = 0.34999999999999998; // [rad] INVENTED -- ~20 deg. Directed out one side; tightness unstated.
inline constexpr double PETROVA_MAX_POWER = 0.050000000000000003; // [W] INVENTED -- 50 mW. Chosen so max output ~= the power a full cell needs to hover. Canon gives capacity but never a discharge rate. See ADR-005.
inline constexpr double PETROVA_SLEW_RATE = 1; // [rad/s] INVENTED -- How fast a cell can re-aim its emission axis.
inline constexpr double CO2_LINE_A = 4.2599999999999999e-06; // [m] CANON -- nu3 asymmetric stretch; strongest IR-active CO2 band.
inline constexpr double CO2_LINE_B = 1.8309999999999999e-05; // [m] CANON -- Book value. Real nu2 bending band is ~15 um; treat as artistic offset.
inline constexpr double CO2_MASS_PER_DIVISION = 2.0999999999999999e-14; // [kg] INVENTED -- = 1x dry mass. Stoichiometric placeholder.
inline constexpr double CO2_DIFFUSIVITY_WATER = 1.92e-09; // [m^2/s] REAL -- in water at 25 C
inline constexpr double CO2_SAT_CONC_1ATM = 1.5; // [kg/m^3] REAL -- CO2-saturated water at 1 atm
inline constexpr double LIFE_DOUBLING_TIME = 691200; // [s] CANON -- ~8 days.
inline constexpr double LIFE_DIVISION_ENERGY_COST = 0; // [J] INVENTED -- Canon silent; default free.
inline constexpr double LIFE_MITOSIS_DURATION = 900; // [s] INVENTED -- 15 min visual division event.
inline constexpr double TAU_DIAMETER = 4.0000000000000003e-05; // [m] INVENTED -- 40 um. Must exceed Astrophage to engulf; size unstated.
inline constexpr double TAU_CRAWL_SPEED = 5.0000000000000004e-06; // [m/s] INVENTED -- Amoeboid crawl; real range 1-10 um/s.
inline constexpr double TAU_DIGEST_TIME = 120; // [s] INVENTED -- Per engulfed cell.
inline constexpr double TAU_N2_LETHAL_CONC = 0.01; // [kg/m^3] INVENTED -- Nitrogen is lethal to Taumoeba.
inline constexpr double TAU_N2_TOLERANCE_INIT = 0; // [-] INVENTED -- Heritable trait in [0,1]. 0.825 => the 'Taumoeba-82.5' strain.
inline constexpr double TAU_MUTATION_SIGMA = 0.02; // [-] INVENTED -- Per-division trait drift; drives the breeding scenario.
inline constexpr double TAU_BIOMASS_YIELD = 0.59999999999999998; // [-] INVENTED -- Fraction of prey biomass converted.
inline constexpr double WATER_VISCOSITY_20C = 0.0010020000000000001; // [Pa*s] REAL
inline constexpr double WATER_DENSITY = 998.20000000000005; // [kg/m^3] REAL -- at 20 C
inline constexpr double WATER_CONDUCTIVITY = 0.59799999999999998; // [W/m/K] REAL
inline constexpr double WATER_SPECIFIC_HEAT = 4182; // [J/kg/K] REAL
inline constexpr double WATER_BOILING_POINT = 373.14999999999998; // [K] REAL -- 3.585 K above the Astrophage setpoint. This gap is why a culture can never boil.
inline constexpr double VF_A = 2.4139999999999999e-05; // [Pa*s] REAL -- Vogel-Fulcher coefficient A
inline constexpr double VF_B = 570.58000000000004; // [K] REAL -- Vogel-Fulcher coefficient B
inline constexpr double VF_C = 140; // [K] REAL -- Vogel-Fulcher coefficient C
inline constexpr double AIR_CONVECTION_H = 10; // [W/m^2/K] REAL -- free convection to room air (Robin BC)
inline constexpr double CONTACT_STIFFNESS = 9.9999999999999995e-07; // [N/m] INVENTED -- Soft-sphere repulsion; tuned so rest overlap < 5%.
inline constexpr double WALL_STICKINESS = 0.14999999999999999; // [-] INVENTED -- Adhesion probability on coverslip contact.
inline constexpr double WALL_STUCK_DRAG_MULT = 20; // [-] INVENTED -- Drag multiplier while adhered.
inline constexpr double DT_PHYSICS = 0.001; // [s] INVENTED -- Fixed physics timestep. Never varies with frame rate.
inline constexpr double TAXIS_MEMORY_TIME = 2; // [s] INVENTED -- Run-and-tumble temporal comparison window. See ADR-007.
inline constexpr double TAXIS_DARK_THRESHOLD = 0.001; // [W/m^2] INVENTED -- Below this irradiance a cell does not move (canon: 'does not move in darkness').
inline constexpr double TAXIS_SEEK_FEED_BELOW = 0.94999999999999996; // [-] INVENTED -- Charge fraction below which a cell seeks light.
inline constexpr double TAXIS_SEEK_BREED_ABOVE = 0.97999999999999998; // [-] INVENTED -- Charge fraction above which a cell seeks CO2.
inline constexpr double CHAMBER_W = 0.0040000000000000001; // [m] INVENTED -- Default culture chamber width. See ADR-009.
inline constexpr double CHAMBER_H = 0.0040000000000000001; // [m] INVENTED -- Default culture chamber height.
inline constexpr double CHAMBER_D = 6.0000000000000002e-05; // [m] INVENTED -- Default slide/coverslip gap (slab depth).
inline constexpr double OPTICS_LAMBDA_VIS = 5.5000000000000003e-07; // [m] REAL -- 550 nm reference for resolution/DOF.
inline constexpr double OPTICS_SENSOR_PIXEL = 6.0000000000000002e-06; // [m] REAL -- Detector pixel pitch for the Berek DOF term.

// ---- Derived quantities --------------------------------------------------
inline constexpr double CELL_RADIUS = 5.0000000000000004e-06; // [m] DERIVED = CELL_DIAMETER / 2
inline constexpr double CELL_VOLUME = 5.2359877559829892e-16; // [m^3] DERIVED = (4/3) pi r^3
inline constexpr double CELL_CROSS_SECTION = 7.8539816339744834e-11; // [m^2] DERIVED = pi r^2 (projected disc, collimated beam)
inline constexpr double CELL_SURFACE_AREA = 3.1415926535897934e-10; // [m^2] DERIVED = 4 pi r^2 (isotropic illumination)
inline constexpr double CELL_DENSITY_DRY = 40.10704565915762; // [kg/m^3] DERIVED = CELL_MASS_DRY / CELL_VOLUME
inline constexpr double CELL_MASS_STORE_MAX = 1.6689750840804278e-11; // [kg] DERIVED = CELL_ENERGY_MAX / c^2
inline constexpr double CELL_MASS_FULL = 1.6710750840804277e-11; // [kg] DERIVED = CELL_MASS_DRY + CELL_MASS_STORE_MAX
inline constexpr double CELL_DENSITY_FULL = 31915.18318909256; // [kg/m^3] DERIVED = CELL_MASS_FULL / CELL_VOLUME
inline constexpr double ENERGY_NEUTRAL_BUOYANCY = 45086.619559568622; // [J] DERIVED = (rho_water * V - m_dry) c^2
inline constexpr double CHARGE_NEUTRAL_BUOYANCY = 0.030057746373045747; // [-] DERIVED = E_neutral / CELL_ENERGY_MAX
inline constexpr double PETROVA_FREQUENCY = 11537579202586.207; // [Hz] DERIVED = c / lambda
inline constexpr double PETROVA_PHOTON_ENERGY = 7.6448809157517267e-21; // [J] DERIVED = h c / lambda
inline constexpr double PETROVA_PHOTON_ENERGY_EV = 0.047715593608836308; // [eV] DERIVED = h c / (lambda * e)
inline constexpr double PETROVA_PHOTONS_PER_FULL_CELL = 1.9620972733654462e+26; // [-] DERIVED = E_max / E_photon
inline constexpr double WATER_VISCOSITY_SETPOINT = 0.00028984712533041231; // [Pa*s] DERIVED = Vogel-Fulcher at CELL_TEMP_SETPOINT
inline constexpr double WATER_THERMAL_DIFFUSIVITY = 1.4325163582348751e-07; // [m^2/s] DERIVED = k / (rho cp)
inline constexpr double DRAG_COEFF_20C = 9.4436275166909197e-08; // [kg/s] DERIVED = 6 pi mu(20C) a
inline constexpr double DRAG_COEFF_SETPOINT = 2.7317447988064303e-08; // [kg/s] DERIVED = 6 pi mu(96.415C) a
inline constexpr double DIFFUSIVITY_20C = 4.2858239975545048e-14; // [m^2/s] DERIVED = Einstein-Stokes kT/gamma at 20 C
inline constexpr double DIFFUSIVITY_SETPOINT = 1.8678155730650127e-13; // [m^2/s] DERIVED = Einstein-Stokes at the setpoint; 4.24x the 20 C value -- drives P4
inline constexpr double CONDUCTION_COEFF = 3.7573448136933928e-05; // [W/K] DERIVED = 4 pi k_water a  (Nu = 2, sphere in still fluid)
inline constexpr double LIFE_GROWTH_RATE = 1.0028171015045505e-06; // [1/s] DERIVED = ln2 / doubling time
inline constexpr double TNT_GRAMS_PER_FULL_CELL = 358.50860420650093; // [g] DERIVED = E_max / 4184 J/g
inline constexpr double WIEN_LAMBDA_AT_SETPOINT = 7.8410346082556516e-06; // [m] DERIVED = Wien b / T -- the THERMAL peak, distinct from the Petrova line

// ---- Field grid resolutions ----------------------------------------------
inline constexpr int FIELD_N_TEMP = 512; // INVENTED -- Temperature grid resolution (NxN).
inline constexpr int FIELD_N_CO2 = 256; // INVENTED -- CO2 grid resolution.
inline constexpr int FIELD_N_N2 = 128; // INVENTED -- N2 grid resolution.
inline constexpr int FIELD_N_IRRAD = 512; // INVENTED -- Irradiance grid resolution.

// ---- Capacity and performance targets ------------------------------------
inline constexpr int MAX_CELLS = 2000000; // INVENTED -- Hard capacity of the cell store.
inline constexpr int MAX_TAUMOEBA = 65536; // INVENTED -- Hard capacity of the taumoeba store.
inline constexpr int DEFAULT_CELLS = 200000; // INVENTED -- Default starting population.
inline constexpr int TARGET_FPS = 144; // INVENTED -- Frame budget target on the reference GPU.

// ---- Objective presets ----------------------------------------------------
struct Objective { const char* name; double magnification; double na; double immersion;
                   double resolution_m; double depth_of_field_m; double fov_m; };
inline constexpr Objective OBJECTIVES[] = {
    { "SURVEY", 10, 0.25, 1, 1.342e-06, 1.1200000000000001e-05, 0.0021999999999999997 },
    { "WORKING", 40, 0.65000000000000002, 1, 5.1615384615384617e-07, 1.5325443786982249e-06, 0.00054999999999999992 },
    { "DETAIL", 100, 1.25, 1.5149999999999999, 2.6839999999999999e-07, 6.06e-07, 0.00021999999999999998 },
};
inline constexpr int OBJECTIVE_COUNT = 3;
inline constexpr int OBJECTIVE_DEFAULT = 1; // WORKING 40x/0.65

// ---- Provenance table (drives the UI parameter inspector) ----------------
struct ParamMeta { const char* key; double value; const char* unit; Provenance prov;
                   const char* note; bool tunable; double tmin; double tmax; bool tlog; };
inline constexpr ParamMeta PARAM_TABLE[] = {
    { "CELL_DIAMETER", 1.0000000000000001e-05, "m", Provenance::Canon, "[REF 1.1] 10 micron sphere.", false, 0.0, 0.0, false },
    { "CELL_MASS_DRY", 2.0999999999999999e-14, "kg", Provenance::Canon, "[REF 1.1] 0.021 ng. Conflicts with 'mostly water' -- see ADR-002.", false, 0.0, 0.0, false },
    { "CELL_TEMP_SETPOINT", 369.565, "K", Provenance::Canon, "[REF 1.4] 96.415 C. NOT a frequency -- see ADR-001.", true, 273.14999999999998, 573.14999999999998, false },
    { "CELL_ENERGY_MAX", 1500000, "J", Provenance::Canon, "[REF 1.3] 1.5 MJ per cell at full enrichment.", true, 1000, 15000000, true },
    { "CELL_ALBEDO", 0, "-", Provenance::Canon, "[REF 1.2] Opaque at ALL wavelengths (super cross-sectionality).", false, 0.0, 0.0, false },
    { "CELL_ALBEDO_DEAD", 0.84999999999999998, "-", Provenance::Invented, "[REF 4] Dead cells go translucent; degree unstated.", true, 0, 1, false },
    { "CELL_LETHAL_TEMP", 573.14999999999998, "K", Provenance::Invented, "300 C. Torch-the-slide escape hatch; canon silent.", true, 373.14999999999998, 1273.1500000000001, false },
    { "PETROVA_WAVELENGTH", 2.5984000000000001e-05, "m", Provenance::Canon, "[REF 1.4] 25.984 micron. NOT 3.11 um -- see ADR-001.", false, 0.0, 0.0, false },
    { "PETROVA_BEAM_HALF_ANGLE", 0.34999999999999998, "rad", Provenance::Invented, "[REF 1.5] ~20 deg. Directed out one side; tightness unstated.", true, 0.02, 3.1415899999999999, false },
    { "PETROVA_MAX_POWER", 0.050000000000000003, "W", Provenance::Invented, "50 mW. Chosen so max output ~= the power a full cell needs to hover. Canon gives capacity but never a discharge rate. See ADR-005.", true, 9.9999999999999995e-07, 100, true },
    { "PETROVA_SLEW_RATE", 1, "rad/s", Provenance::Invented, "How fast a cell can re-aim its emission axis.", true, 0.01, 100, true },
    { "CO2_LINE_A", 4.2599999999999999e-06, "m", Provenance::Canon, "[REF 1.5] nu3 asymmetric stretch; strongest IR-active CO2 band.", false, 0.0, 0.0, false },
    { "CO2_LINE_B", 1.8309999999999999e-05, "m", Provenance::Canon, "[REF 3.2] Book value. Real nu2 bending band is ~15 um; treat as artistic offset.", false, 0.0, 0.0, false },
    { "CO2_MASS_PER_DIVISION", 2.0999999999999999e-14, "kg", Provenance::Invented, "= 1x dry mass. Stoichiometric placeholder.", true, 2.0999999999999998e-15, 2.0999999999999999e-13, true },
    { "CO2_DIFFUSIVITY_WATER", 1.92e-09, "m^2/s", Provenance::Real, "in water at 25 C", false, 0.0, 0.0, false },
    { "CO2_SAT_CONC_1ATM", 1.5, "kg/m^3", Provenance::Real, "CO2-saturated water at 1 atm", false, 0.0, 0.0, false },
    { "LIFE_DOUBLING_TIME", 691200, "s", Provenance::Canon, "[REF 1.6] ~8 days.", true, 3600, 6912000, true },
    { "LIFE_DIVISION_ENERGY_COST", 0, "J", Provenance::Invented, "Canon silent; default free.", true, 0, 100000, false },
    { "LIFE_MITOSIS_DURATION", 900, "s", Provenance::Invented, "15 min visual division event.", true, 1, 10000, true },
    { "TAU_DIAMETER", 4.0000000000000003e-05, "m", Provenance::Invented, "[REF 1.8] 40 um. Must exceed Astrophage to engulf; size unstated.", true, 1.5e-05, 0.00020000000000000001, true },
    { "TAU_CRAWL_SPEED", 5.0000000000000004e-06, "m/s", Provenance::Invented, "Amoeboid crawl; real range 1-10 um/s.", true, 9.9999999999999995e-08, 0.0001, true },
    { "TAU_DIGEST_TIME", 120, "s", Provenance::Invented, "Per engulfed cell.", true, 1, 10000, true },
    { "TAU_N2_LETHAL_CONC", 0.01, "kg/m^3", Provenance::Invented, "[REF 1.8] Nitrogen is lethal to Taumoeba.", true, 0.0001, 1, true },
    { "TAU_N2_TOLERANCE_INIT", 0, "-", Provenance::Invented, "[REF 1.8] Heritable trait in [0,1]. 0.825 => the 'Taumoeba-82.5' strain.", true, 0, 1, false },
    { "TAU_MUTATION_SIGMA", 0.02, "-", Provenance::Invented, "Per-division trait drift; drives the breeding scenario.", true, 0, 0.5, false },
    { "TAU_BIOMASS_YIELD", 0.59999999999999998, "-", Provenance::Invented, "Fraction of prey biomass converted.", true, 0, 1, false },
    { "WATER_VISCOSITY_20C", 0.0010020000000000001, "Pa*s", Provenance::Real, "", false, 0.0, 0.0, false },
    { "WATER_DENSITY", 998.20000000000005, "kg/m^3", Provenance::Real, "at 20 C", true, 500, 2000, false },
    { "WATER_CONDUCTIVITY", 0.59799999999999998, "W/m/K", Provenance::Real, "", false, 0.0, 0.0, false },
    { "WATER_SPECIFIC_HEAT", 4182, "J/kg/K", Provenance::Real, "", false, 0.0, 0.0, false },
    { "WATER_BOILING_POINT", 373.14999999999998, "K", Provenance::Real, "3.585 K above the Astrophage setpoint. This gap is why a culture can never boil.", false, 0.0, 0.0, false },
    { "VF_A", 2.4139999999999999e-05, "Pa*s", Provenance::Real, "Vogel-Fulcher coefficient A", false, 0.0, 0.0, false },
    { "VF_B", 570.58000000000004, "K", Provenance::Real, "Vogel-Fulcher coefficient B", false, 0.0, 0.0, false },
    { "VF_C", 140, "K", Provenance::Real, "Vogel-Fulcher coefficient C", false, 0.0, 0.0, false },
    { "AIR_CONVECTION_H", 10, "W/m^2/K", Provenance::Real, "free convection to room air (Robin BC)", false, 0.0, 0.0, false },
    { "CONTACT_STIFFNESS", 9.9999999999999995e-07, "N/m", Provenance::Invented, "Soft-sphere repulsion; tuned so rest overlap < 5%.", true, 1.0000000000000001e-09, 0.001, true },
    { "WALL_STICKINESS", 0.14999999999999999, "-", Provenance::Invented, "Adhesion probability on coverslip contact.", true, 0, 1, false },
    { "WALL_STUCK_DRAG_MULT", 20, "-", Provenance::Invented, "Drag multiplier while adhered.", true, 1, 1000, true },
    { "DT_PHYSICS", 0.001, "s", Provenance::Invented, "Fixed physics timestep. Never varies with frame rate.", true, 1.0000000000000001e-05, 0.01, true },
    { "TAXIS_MEMORY_TIME", 2, "s", Provenance::Invented, "Run-and-tumble temporal comparison window. See ADR-007.", true, 0.050000000000000003, 60, true },
    { "TAXIS_DARK_THRESHOLD", 0.001, "W/m^2", Provenance::Invented, "[REF 1.5] Below this irradiance a cell does not move (canon: 'does not move in darkness').", true, 0, 1000, true },
    { "TAXIS_SEEK_FEED_BELOW", 0.94999999999999996, "-", Provenance::Invented, "Charge fraction below which a cell seeks light.", true, 0, 1, false },
    { "TAXIS_SEEK_BREED_ABOVE", 0.97999999999999998, "-", Provenance::Invented, "Charge fraction above which a cell seeks CO2.", true, 0, 1, false },
    { "CHAMBER_W", 0.0040000000000000001, "m", Provenance::Invented, "Default culture chamber width. See ADR-009.", true, 0.0001, 0.02, true },
    { "CHAMBER_H", 0.0040000000000000001, "m", Provenance::Invented, "Default culture chamber height.", true, 0.0001, 0.02, true },
    { "CHAMBER_D", 6.0000000000000002e-05, "m", Provenance::Invented, "Default slide/coverslip gap (slab depth).", true, 1.0000000000000001e-05, 0.001, true },
    { "OPTICS_LAMBDA_VIS", 5.5000000000000003e-07, "m", Provenance::Real, "550 nm reference for resolution/DOF.", false, 0.0, 0.0, false },
    { "OPTICS_SENSOR_PIXEL", 6.0000000000000002e-06, "m", Provenance::Real, "Detector pixel pitch for the Berek DOF term.", false, 0.0, 0.0, false },
    { "CELL_RADIUS", 5.0000000000000004e-06, "m", Provenance::Derived, "= CELL_DIAMETER / 2", false, 0.0, 0.0, false },
    { "CELL_VOLUME", 5.2359877559829892e-16, "m^3", Provenance::Derived, "= (4/3) pi r^3", false, 0.0, 0.0, false },
    { "CELL_CROSS_SECTION", 7.8539816339744834e-11, "m^2", Provenance::Derived, "= pi r^2 (projected disc, collimated beam)", false, 0.0, 0.0, false },
    { "CELL_SURFACE_AREA", 3.1415926535897934e-10, "m^2", Provenance::Derived, "= 4 pi r^2 (isotropic illumination)", false, 0.0, 0.0, false },
    { "CELL_DENSITY_DRY", 40.10704565915762, "kg/m^3", Provenance::Derived, "= CELL_MASS_DRY / CELL_VOLUME", false, 0.0, 0.0, false },
    { "CELL_MASS_STORE_MAX", 1.6689750840804278e-11, "kg", Provenance::Derived, "= CELL_ENERGY_MAX / c^2", false, 0.0, 0.0, false },
    { "CELL_MASS_FULL", 1.6710750840804277e-11, "kg", Provenance::Derived, "= CELL_MASS_DRY + CELL_MASS_STORE_MAX", false, 0.0, 0.0, false },
    { "CELL_DENSITY_FULL", 31915.18318909256, "kg/m^3", Provenance::Derived, "= CELL_MASS_FULL / CELL_VOLUME", false, 0.0, 0.0, false },
    { "ENERGY_NEUTRAL_BUOYANCY", 45086.619559568622, "J", Provenance::Derived, "= (rho_water * V - m_dry) c^2", false, 0.0, 0.0, false },
    { "CHARGE_NEUTRAL_BUOYANCY", 0.030057746373045747, "-", Provenance::Derived, "= E_neutral / CELL_ENERGY_MAX", false, 0.0, 0.0, false },
    { "PETROVA_FREQUENCY", 11537579202586.207, "Hz", Provenance::Derived, "= c / lambda", false, 0.0, 0.0, false },
    { "PETROVA_PHOTON_ENERGY", 7.6448809157517267e-21, "J", Provenance::Derived, "= h c / lambda", false, 0.0, 0.0, false },
    { "PETROVA_PHOTON_ENERGY_EV", 0.047715593608836308, "eV", Provenance::Derived, "= h c / (lambda * e)", false, 0.0, 0.0, false },
    { "PETROVA_PHOTONS_PER_FULL_CELL", 1.9620972733654462e+26, "-", Provenance::Derived, "= E_max / E_photon", false, 0.0, 0.0, false },
    { "WATER_VISCOSITY_SETPOINT", 0.00028984712533041231, "Pa*s", Provenance::Derived, "= Vogel-Fulcher at CELL_TEMP_SETPOINT", false, 0.0, 0.0, false },
    { "WATER_THERMAL_DIFFUSIVITY", 1.4325163582348751e-07, "m^2/s", Provenance::Derived, "= k / (rho cp)", false, 0.0, 0.0, false },
    { "DRAG_COEFF_20C", 9.4436275166909197e-08, "kg/s", Provenance::Derived, "= 6 pi mu(20C) a", false, 0.0, 0.0, false },
    { "DRAG_COEFF_SETPOINT", 2.7317447988064303e-08, "kg/s", Provenance::Derived, "= 6 pi mu(96.415C) a", false, 0.0, 0.0, false },
    { "DIFFUSIVITY_20C", 4.2858239975545048e-14, "m^2/s", Provenance::Derived, "= Einstein-Stokes kT/gamma at 20 C", false, 0.0, 0.0, false },
    { "DIFFUSIVITY_SETPOINT", 1.8678155730650127e-13, "m^2/s", Provenance::Derived, "= Einstein-Stokes at the setpoint; 4.24x the 20 C value -- drives P4", false, 0.0, 0.0, false },
    { "CONDUCTION_COEFF", 3.7573448136933928e-05, "W/K", Provenance::Derived, "= 4 pi k_water a  (Nu = 2, sphere in still fluid)", false, 0.0, 0.0, false },
    { "LIFE_GROWTH_RATE", 1.0028171015045505e-06, "1/s", Provenance::Derived, "= ln2 / doubling time", false, 0.0, 0.0, false },
    { "TNT_GRAMS_PER_FULL_CELL", 358.50860420650093, "g", Provenance::Derived, "= E_max / 4184 J/g", false, 0.0, 0.0, false },
    { "WIEN_LAMBDA_AT_SETPOINT", 7.8410346082556516e-06, "m", Provenance::Derived, "= Wien b / T -- the THERMAL peak, distinct from the Petrova line", false, 0.0, 0.0, false },
};
inline constexpr int PARAM_COUNT = 72;

} // namespace astro::canon
